var numero1 = 7;
var numero2 = 10;
var soma = numero1 + numero2;
var sub = numero1 - numero2;
var mult = numero1 * numero2;
var divi = numero1 / numero2;
console.log(`a soma de ${numero1} e ${numero2} é igual a ${soma}`);
console.log(`a subtração de ${numero1} e ${numero2} é igual a ${sub}`);
console.log(`a multiplicação de ${numero1} e ${numero2} é igual a ${mult}`);
console.log(`a divisão de ${numero1} e ${numero2} é igual a ${divi}`);